name: PR Linked Issue
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_linked_issues:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - uses: nearform/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-labels: 'renovate'
          exclude-branches: 'renovate/**'
      # OPTIONAL: Use the output from the `check-linked-issues` step
      - name: Get the output
        run: echo "How many linked issues? ${{ steps.check-linked-issues.outputs.linked_issues_count }}"
