name: PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: '[FEATURE],[DEFECT],[CHORE],[DOCS]' # title should start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 100 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
